#!/bin/bash

BACKUP_FOLDER="$HOME/repos/dotfiles"
SUBLIME_3="$HOME/.config/sublime-text-3/Packages"

function backup {
  create_folders
  backup_dotfiles
  backup_sublime
}

function create_folders {
  mkdir -p $BACKUP_FOLDER/dotfiles
  mkdir -p $BACKUP_FOLDER/Sublime_3
}

function backup_dotfiles {
  FILES=('.bash_aliases' '.bash_env' '.vimrc' '.tmux.conf'
         '.gitconfig' '.gitignore' '.jshintrc'
         '.jsbeautifyrc' '.face' '.juliarc' '.julia/v0.3/REQUIRE')

  for FILE in "${FILES[@]}"; do
    cp $HOME/$FILE $BACKUP_FOLDER/dotfiles
  done
}

function backup_sublime {
  cp -r $SUBLIME_3/User $BACKUP_FOLDER/Sublime_3
  cp -r $SUBLIME_3/Themes $BACKUP_FOLDER/Sublime_3
}

$@
